--- 
abstract: Catalyst Apache Engines
author: Sebastian Riedel, <sri@cpan.org>
distribution_type: module
generated_by: Module::Install version 0.65
license: perl
meta-spec: 
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
  version: 1.3
name: Catalyst-Engine-Apache
no_index: 
  directory: 
    - inc
    - t
requires: 
  Catalyst::Runtime: 0
tests: t/0*.t
version: 1.11
